name: Publish Python Package to PyPI

# Trigger the workflow on release creation
on:
  release:
    types: [published] # Runs when a release is published on GitHub

jobs:
  build-and-publish:
    name: Build and publish Python distribution to PyPI
    runs-on: ubuntu-latest
    # (Optional) Specify the environment configured for Trusted Publishing
    environment: release
    # Grant GITHUB_TOKEN permissions to fetch OIDC token
    permissions:
      id-token: write # Required for trusted publishing

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use an appropriate Python version

    - name: Install build dependencies
      run: python -m pip install --upgrade build

    - name: Build package
      run: python -m build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # No API token needed here when using Trusted Publishing!